config/routes.rb
Rails.application.routes.draw do
    
  root 'pages#home'  
  
  get '/home', to: 'pages#home'
  
  get '/videos', to: 'pages#videos' 

  resources :recipes do
    member do
      post 'like'
    end
  end
  
  resources :chefs, except: [:new, :destroy]
  
  get '/register', to: 'chefs#new'
  
  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get '/logout', to: 'logins#destroy'
  
  resources :styles
  resources :ingredients
  
end

app/views/pages/home.html.erb
<div class="center jumbotron">
  <div class="well-reverse">
    <H1> Welcome to the Eat Well App</H1>
    <h2> Come and join us to share recipes and have fun preparing meals again.</h2>
    <%= link_to "Sign up now!", register_path, class: "btn btn-lg btn-success" %><br><br>
  </div>
</div>

<div class="row">
  <div class="col-lg-4">
    <h3 class="midrow">
      View Recipes as Guest 
    </h3>
    <h2 class="left">Browse and view recipes as a guest and Sign up later</h2>
    <p><%= link_to "Browse Recipes", recipes_path, class: "btn btn-warning btn-small" %></p>
  </div>
  <div class="col-lg-4">
    <h3 class="midrow">
      Sign in to your account
    </h3>
    <h2 class="left">Add/update your recipes/create reviews/like-dislike recipes and much much more!</h2>
    <p><%= link_to "Log Me In",  login_path, class: "btn btn-warning btn-small" %></p>
  </div>
  <div class="col-lg-4">
    <h3 class="midrow">
      Food Hacks
    </h3>
    <h2 class="left">Find speedy ways to do cyt a butternut sqash or deseed a pomegranite and much more</h2>
    <p><%= link_to "Food Hacks", videos_path, class: "btn btn-warning btn-small" %></p>
  </div>
</div>

app/views/pages/videos.html.erb
<p><H1>Food Hacks</H1></p>

  <div class="row center">
    <p><H2>How to Prepare, Peel, and Cut a Butternut Squash</H2></p>
    <p><iframe width="560" height="315" src="https://www.youtube.com/embed/lsMJy7HpnEo" frameborder="0" allowfullscreen></iframe></p>
  </div>
  
  <div class="row center">
    <p><H2>How to quickly deseed a pomegranate<H2></p>
    <p><iframe width="560" height="315" src="https://www.youtube.com/embed/5ScRDjrqIMc" frameborder="0" allowfullscreen></iframe></p>
  </div>
  
  <div class="row center">
    <p><H2>Mason Jar Lid Egg Tip<H2></p>
    <p><iframe width="560" height="315" src="https://www.youtube.com/embed/5KZUDNMEdRg" frameborder="0" allowfullscreen></iframe></p>
  </div>
  
  <div class="row center">
    <p><H2>How to make Two Ingredient Cookies, but works awesome for a cake or muffins too</H2></p>
    <p><iframe width="560" height="315" src="https://www.youtube.com/embed/aCNzeV87_f4" frameborder="0" allowfullscreen></iframe></p>
  </div>